### ISSUE TITLE
[feature request][Neovim] highlight the jump markers

### ISSUE THREAD

**Issue by idanarye** [zsugabubus/vim-jumpmotion#1]
Say I have this buffer:
![image](https://user-images.githubusercontent.com/1149255/77249938-412d7080-6c4d-11ea-89a5-e0a658bf1be6.png)

If I use easymotion for word-jump (`<Leader><Leader>w`), I get this:
![image](https://user-images.githubusercontent.com/1149255/77249948-4f7b8c80-6c4d-11ea-871c-8b3be8952c3d.png)

Thanks to the highlighting, I can clearly see which characters are the jump markers and which are the original text.

jumpmotion does not have that feature:
![image](https://user-images.githubusercontent.com/1149255/77249990-88b3fc80-6c4d-11ea-950d-3f569c43ce8c.png)

Making it much harder to use, as you can't easily notice where the jump markers are.

**Comment by idanarye** [comment]
Almost forgot to mention - I'm using Neovim. When I tried it with regular Vim, I got this:

![image](https://user-images.githubusercontent.com/1149255/77250579-95d2ea80-6c51-11ea-8738-2f89f49af089.png)

Which is better (has highlighting) but worse (only covers the first visual line of each logical line)

**Comment by zsugabubus** [comment]
Hmmm. Is it possible that you already have a highlight named `JumpMotion` in NeoVim? If you manually add `highlight JumpMotion cterm=bold ctermfg=196 ctermbg=226` (or with different colors) does that help? It writes the labels but highlights are seem invisible...

> Which is better (has highlighting) but worse (only covers the first visual line of each logical line)

Ah yeah, word wrapping. Will fix it.

**Comment by zsugabubus** [comment]
Just to make sure I tried `nvim -u NONE` (no config at all) and shows the markers. Did you use the same vimrc? What colorscheme do you use?

**Comment by idanarye** [comment]
The highlight group exists - but when I `:highlight JumpMotion` it shows plain formatted text. I experimented a bit and it looks like even in terminal mode Neovim is using the `gui` colors. I've sent a PR.

**Comment by zsugabubus** [comment]
Thanks! Hope it works now.

**Comment by idanarye** [comment]
Works fine
