### ISSUE TITLE
Just doesn't work

### ISSUE THREAD

**Issue by 097115** [zsugabubus/vim-jumpmotion#3]
So, let's say I run it in the following manner:

    vim --clean -c 'source ./vim-jumpmotion/plugin/jumpmotion.vim' ~/.vimrc

After pressing `<Space>`, `umpMotion)` flickers on the screen, but pressing any key consequently after that (like, `<Space>n` or `<Space>j`) results in nothing.

![](https://i.imgur.com/Y88088V.jpg)

    VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 22 2020 17:14:43)
    macOS version
    Included patches: 1-426

**Comment by zsugabubus** [comment]
I lived in a lie. I thought NeoVim help shows compatibility notices. It seems that Vim does not support `<Cmd>` mappings.

**Comment by zsugabubus** [comment]
Could you try it now? It already works on my machine™.

**Comment by 097115** [comment]
Yeah, thanks, it works now. This particular bug is resolved then, I think.

Thanks once again, good luck, and keep improving :)
