### ISSUE TITLE
Add guide or example how use this plugin?

### ISSUE THREAD

**Issue by TeoDev1611** [zsugabubus/vim-jumpmotion#6]
Hi is awesome your work but idk how can use please can you provide a example ?

**Comment by zsugabubus** [comment]
Hi!

What do you mean exactly?

1. Install the plugin and load it (just like others).
3. Press `<Space>w` (`<Plug>(JumpMotion){motion}`).
  `<Plug>(JumpMotion)` is automatically mapped to an unused key. If you do not like it or `<Space>` is already mapped + for available built-in mappings: `:h <Plug>(JumpMotion)`.
4. Enter letters you see on the screen.

**Comment by TeoDev1611** [comment]
Thanks
